"""
Internal canonical types for the Lazarus inference server.

All protocol routers translate *to* these types before touching the engine,
and translate *from* these types before writing a response.  The engine
itself is completely unaware of any wire format.

Design rules
------------
- No raw dicts.  Every value has a named type.
- All constrained strings are enums or Literals.
- Pydantic models only — no dataclasses or NamedTuples.
- JSON Schema parameters (tool definitions) are dict[str, Any] by necessity —
  JSON Schema is inherently recursive and untyped.
"""

from __future__ import annotations

import uuid
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field

# ── Enumerations ──────────────────────────────────────────────────────────────


class MessageRole(str, Enum):
    """Role of a chat participant."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class StopReason(str, Enum):
    """Why the model stopped generating (internal vocabulary).

    Values match the string literals emitted by ``generation.py``.
    """

    EOS = "eos"
    STOP_TOKEN = "stop_token"
    MAX_TOKENS = "max_tokens"
    PLUGIN = "plugin"


class FinishReason(str, Enum):
    """OpenAI-compatible finish reason (used in responses)."""

    STOP = "stop"
    LENGTH = "length"
    TOOL_CALLS = "tool_calls"


# ── Tool definitions (sent by the caller) ────────────────────────────────────


class ToolFunctionDef(BaseModel):
    """Definition of a callable function."""

    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = None  # JSON Schema — inherently untyped


class Tool(BaseModel):
    """A tool the model may call."""

    type: Literal["function"] = "function"
    function: ToolFunctionDef


# ── Tool calls (generated by the model) ──────────────────────────────────────


class ToolCallFunction(BaseModel):
    """The function name + serialised arguments produced by the model."""

    name: str
    arguments: str  # JSON-encoded string


class ToolCall(BaseModel):
    """A single tool call produced by the model."""

    id: str = Field(default_factory=lambda: f"call_{uuid.uuid4().hex[:8]}")
    type: Literal["function"] = "function"
    function: ToolCallFunction


# ── Message ───────────────────────────────────────────────────────────────────


class InternalMessage(BaseModel):
    """A single turn in the conversation.

    Fields are optional to accommodate all role types:
    - ``role=TOOL``: content + tool_call_id required
    - ``role=ASSISTANT`` with tool calls: tool_calls set, content may be None
    """

    role: MessageRole
    content: str | None = None
    name: str | None = None  # tool function name (role=TOOL)
    tool_call_id: str | None = None  # which tool call this result answers
    tool_calls: list[ToolCall] | None = None  # set by assistant when calling tools


# ── Request ───────────────────────────────────────────────────────────────────


class InternalRequest(BaseModel):
    """Everything the engine needs to run a generation."""

    messages: list[InternalMessage]
    model: str
    max_tokens: int = Field(512, ge=1)
    temperature: float = Field(0.7, ge=0.0)
    top_p: float = Field(0.9, ge=0.0, le=1.0)
    stream: bool = False
    stop: list[str] | None = None
    tools: list[Tool] | None = None
    chat_template_kwargs: dict[str, Any] | None = None
    conversation_id: str | None = Field(
        default=None,
        description=(
            "Optional per-conversation identifier used by the torch "
            "residual-bounded KV-direct runtime to key the WARM residual "
            "cache so multi-turn chats can skip the split-prefill forward."
        ),
    )


# ── Response ──────────────────────────────────────────────────────────────────


class InternalUsage(BaseModel):
    """Token accounting for a completed generation."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class InternalResponse(BaseModel):
    """Complete (non-streaming) generation result."""

    content: str | None  # None when the response is a tool call
    model: str
    finish_reason: FinishReason
    usage: InternalUsage
    tool_calls: list[ToolCall] | None = None


# ── Streaming chunk ───────────────────────────────────────────────────────────


class InternalChunk(BaseModel):
    """One incremental piece of a streaming generation.

    ``finish_reason`` is ``None`` for every chunk except the last.
    The last chunk has ``content=""`` (or None) and a non-None ``finish_reason``.
    When ``tool_calls`` is set the client should treat the chunk as a tool-call
    result rather than text content.
    """

    content: str | None = None
    finish_reason: FinishReason | None = None
    tool_calls: list[ToolCall] | None = None
